name: Angular Testing

on:
  push:
    branches:
      - main
      - dev
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Set CHROME_BIN Environment Variable
        run: echo "export CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build Angular app
        run: npm run build
        working-directory: ./frontend

      - name: Run unit tests
        run: npm test
        working-directory: ./frontend

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./coverage
